//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace AppStore.Models
{
    public partial class Apps
    {
        public Apps()
        {
            this.Scores = new HashSet<Scores>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int GenreId { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual ICollection<Scores> Scores { get; set; }
    }
}
