//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AppId { get; set; }
        public int Score { get; set; }
    
        public virtual Apps Apps { get; set; }
        public virtual Users Users { get; set; }
    }
}
